theme: jekyll-theme-giellalt
title: Dictionary for Norwegian Bokmål ⇒ Swedish
description: An electronic dictionary from Norwegian Bokmål to Swedish

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
